// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAk48m_Uv6iVfU8uzPlEw3cN_b8AwtjsEE',
    appId: '1:98121756613:web:51999e1627ec547ceee5ac',
    messagingSenderId: '98121756613',
    projectId: 'safepet-30afd',
    authDomain: 'safepet-30afd.firebaseapp.com',
    databaseURL: 'https://safepet-30afd-default-rtdb.firebaseio.com',
    storageBucket: 'safepet-30afd.appspot.com',
    measurementId: 'G-8TD87R78H9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl1Gc-HoBH1qWBq-gdUwM3XoMuxsuTx3E',
    appId: '1:98121756613:android:75c7a0874cbb5ca6eee5ac',
    messagingSenderId: '98121756613',
    projectId: 'safepet-30afd',
    databaseURL: 'https://safepet-30afd-default-rtdb.firebaseio.com',
    storageBucket: 'safepet-30afd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANsLCr9xxrWqL1SYDs9OpMogVWeVC_LwE',
    appId: '1:98121756613:ios:b740703e9a06114deee5ac',
    messagingSenderId: '98121756613',
    projectId: 'safepet-30afd',
    databaseURL: 'https://safepet-30afd-default-rtdb.firebaseio.com',
    storageBucket: 'safepet-30afd.appspot.com',
    iosClientId:
        '98121756613-cfpi3a8p3qa25h101oav491lr77ce1ap.apps.googleusercontent.com',
    iosBundleId: 'com.javeriana.safepet',
  );
}
